spring:
  application:
    name: fan-cloud-eureka-server
  security:
    user:
      name: admin
      password: 123456

server:
  port: 8081

eureka:
  server:
    enable-self-preservation: false #关闭自我保护模式 生产环境不建议关闭
    eviction-interval-timer-in-ms: 2000 #间隔2秒剔除
  client:
    register-with-eureka: false # 是否注册自身到eureka服务器
    fetch-registry: false # 因为自己是注册中心，不需要去检索服务信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: 127.0.0.1

